[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y libpq-dev postgresql-client pkg-config && \
cargo build --release 
"""

[deploy]
startCommand = "./target/release/pictoria_api"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
rust-version = "1.83.0"
apt = ["libpq-dev", "postgresql-client", "pkg-config"]
pkgs = ["postgresql"]

[provision]
postgresql = true

[variables]
RUST_LOG = "info"
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"