[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y libpq-dev postgresql-client pkg-config && \
cargo build --release && \
mkdir -p /app/bin && \
cp target/release/pictoria_api /app/bin/
"""

[deploy]
startCommand = "/app/bin/pictoria_api"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
healthcheckInterval = 15

[nixpacks]
rust-version = "1.70.0"
apt = ["libpq-dev", "postgresql-client", "pkg-config"]
pkgs = ["postgresql"]

[provision]
postgresql = true

[variables]
RUST_LOG = "info"
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig"
ADDRESS = "0.0.0.0"
PORT = "8000"